version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
    POSTGRES_DB: company_data
    POSTGRES_USER: bob
    POSTGRES_PASSWORD: bobssecret
    PGDATA: /var/lib/postgresql/data
    volumes:
    - db-data:/var/lib/postgresql/data
    ports:
    - "10001:5432"
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spring.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "10002:80"
    volumes:
    - pgadmin-data:/var/lib/pgadmin
    links:
    - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data: